package dobotdll;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * ARC related<br>
 * <i>native declaration : line 220</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ARCParams extends Structure {
	public float xyzVelocity;
	public float rVelocity;
	public float xyzAcceleration;
	public float rAcceleration;
	public ARCParams() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("xyzVelocity", "rVelocity", "xyzAcceleration", "rAcceleration");
	}
	public ARCParams(float xyzVelocity, float rVelocity, float xyzAcceleration, float rAcceleration) {
		super();
		this.xyzVelocity = xyzVelocity;
		this.rVelocity = rVelocity;
		this.xyzAcceleration = xyzAcceleration;
		this.rAcceleration = rAcceleration;
	}
	public ARCParams(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ARCParams implements Structure.ByReference {
		
	};
	public static class ByValue extends ARCParams implements Structure.ByValue {
		
	};
}
