package dobotdll;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 35</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AutoLevelingCmd extends Structure {
	public byte controlFlag;
	public float precision;
	public AutoLevelingCmd() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("controlFlag", "precision");
	}
	public AutoLevelingCmd(byte controlFlag, float precision) {
		super();
		this.controlFlag = controlFlag;
		this.precision = precision;
	}
	public AutoLevelingCmd(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends AutoLevelingCmd implements Structure.ByReference {
		
	};
	public static class ByValue extends AutoLevelingCmd implements Structure.ByValue {
		
	};
}
