package dobotdll;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * End effector<br>
 * <i>native declaration : line 51</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class EndEffectorParams extends Structure {
	public float xBias;
	public float yBias;
	public float zBias;
	public EndEffectorParams() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("xBias", "yBias", "zBias");
	}
	public EndEffectorParams(float xBias, float yBias, float zBias) {
		super();
		this.xBias = xBias;
		this.yBias = yBias;
		this.zBias = zBias;
	}
	public EndEffectorParams(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends EndEffectorParams implements Structure.ByReference {
		
	};
	public static class ByValue extends EndEffectorParams implements Structure.ByValue {
		
	};
}
