package dobotdll;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * HOME related<br>
 * <i>native declaration : line 24</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class HOMEParams extends Structure {
	public float x;
	public float y;
	public float z;
	public float r;
	public HOMEParams() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("x", "y", "z", "r");
	}
	public HOMEParams(float x, float y, float z, float r) {
		super();
		this.x = x;
		this.y = y;
		this.z = z;
		this.r = r;
	}
	public HOMEParams(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends HOMEParams implements Structure.ByReference {
		
	};
	public static class ByValue extends HOMEParams implements Structure.ByValue {
		
	};
}
