package dobotdll;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 309</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IOPWM extends Structure {
	public byte address;
	public float frequency;
	public float dutyCycle;
	public IOPWM() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("address", "frequency", "dutyCycle");
	}
	public IOPWM(byte address, float frequency, float dutyCycle) {
		super();
		this.address = address;
		this.frequency = frequency;
		this.dutyCycle = dutyCycle;
	}
	public IOPWM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends IOPWM implements Structure.ByReference {
		
	};
	public static class ByValue extends IOPWM implements Structure.ByValue {
		
	};
}
