package dobotdll;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 102</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class JOGCmd extends Structure {
	public byte isJoint;
	public byte cmd;
	public JOGCmd() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("isJoint", "cmd");
	}
	public JOGCmd(byte isJoint, byte cmd) {
		super();
		this.isJoint = isJoint;
		this.cmd = cmd;
	}
	public JOGCmd(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends JOGCmd implements Structure.ByReference {
		
	};
	public static class ByValue extends JOGCmd implements Structure.ByValue {
		
	};
}
