package dobotdll;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 176</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ParallelOutputCmd extends Structure {
	public byte ratio;
	public short address;
	public byte level;
	public ParallelOutputCmd() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("ratio", "address", "level");
	}
	public ParallelOutputCmd(byte ratio, short address, byte level) {
		super();
		this.ratio = ratio;
		this.address = address;
		this.level = level;
	}
	public ParallelOutputCmd(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ParallelOutputCmd implements Structure.ByReference {
		
	};
	public static class ByValue extends ParallelOutputCmd implements Structure.ByValue {
		
	};
}
