package dobotdll;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 402</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PIDParams extends Structure {
	public float p;
	public float i;
	public float d;
	public float v;
	public float a;
	public PIDParams() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("p", "i", "d", "v", "a");
	}
	public PIDParams(float p, float i, float d, float v, float a) {
		super();
		this.p = p;
		this.i = i;
		this.d = d;
		this.v = v;
		this.a = a;
	}
	public PIDParams(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PIDParams implements Structure.ByReference {
		
	};
	public static class ByValue extends PIDParams implements Structure.ByValue {
		
	};
}
