package dobotdll;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 132</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PTPJump2Params extends Structure {
	public float startJumpHeight;
	public float endJumpHeight;
	public float zLimit;
	public PTPJump2Params() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("startJumpHeight", "endJumpHeight", "zLimit");
	}
	public PTPJump2Params(float startJumpHeight, float endJumpHeight, float zLimit) {
		super();
		this.startJumpHeight = startJumpHeight;
		this.endJumpHeight = endJumpHeight;
		this.zLimit = zLimit;
	}
	public PTPJump2Params(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PTPJump2Params implements Structure.ByReference {
		
	};
	public static class ByValue extends PTPJump2Params implements Structure.ByValue {
		
	};
}
