package dobotdll;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 284</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TRIGCmd extends Structure {
	public byte address;
	public byte mode;
	public byte condition;
	public short threshold;
	public TRIGCmd() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("address", "mode", "condition", "threshold");
	}
	public TRIGCmd(byte address, byte mode, byte condition, short threshold) {
		super();
		this.address = address;
		this.mode = mode;
		this.condition = condition;
		this.threshold = threshold;
	}
	public TRIGCmd(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TRIGCmd implements Structure.ByReference {
		
	};
	public static class ByValue extends TRIGCmd implements Structure.ByValue {
		
	};
}
