package dobotdll;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 263</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class WAITCmd extends Structure {
	public int timeout;
	public WAITCmd() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("timeout");
	}
	public WAITCmd(int timeout) {
		super();
		this.timeout = timeout;
	}
	public WAITCmd(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends WAITCmd implements Structure.ByReference {
		
	};
	public static class ByValue extends WAITCmd implements Structure.ByValue {
		
	};
}
