package dobotdll;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 350</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class WIFIGateway extends Structure {
	/** C type : uint8_t[4] */
	public byte[] addr = new byte[4];
	public WIFIGateway() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("addr");
	}
	/** @param addr C type : uint8_t[4] */
	public WIFIGateway(byte addr[]) {
		super();
		if ((addr.length != this.addr.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.addr = addr;
	}
	public WIFIGateway(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends WIFIGateway implements Structure.ByReference {
		
	};
	public static class ByValue extends WIFIGateway implements Structure.ByValue {
		
	};
}
